### ISSUE TITLE
Ksid6! We need to work on this page...

### ISSUE THREAD

**Issue by Jme7** [Ksid6/Ksid6.github.io#1]
@Ksid6 What are you thinking of?

**Comment by Ksid6** [comment]
I want a fun website for kids! 👾

**Comment by Jme7** [comment]
Hmmm, ok
I am going to put the "fun website for kids" at a website like `https://ksid6.github.io/INSERT-NAME-OF-KIDS-WEBSITE-HERE`, so you can have your website have other uses!
